name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup Chrome driver
      #   uses: nanasess/setup-chromedriver@v2
      #   with:
      #     # Optional: do not specify to match Chrome's version
      #     chromedriver-version: '117.0.5938.88'
      # - run: chromedriver --url-base=/wd/hub &        

      - name: Download and set up ChromeDriver
        run: |
         CHROMEDRIVER_VERSION="117.0.5938.88"
         CHROMEDRIVER_URL="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/win64/chromedriver-win64.zip"
         wget "$CHROMEDRIVER_URL" -O chromedriver-win64.zip
         unzip chromedriver-win64.zip
         sudo mv chromedriver /usr/local/bin/      

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm install cypress --save-dev
          npm install -g @axe-core/cli
        
      - name: Run Cypress Tests
        run: npx cypress run

      - name: Run Accessibility Checks
        run: 
          npx axe --stdout https://qxf2.com/selenium-tutorial-main --tags wcag2a --verbose --show-errors --exit        

