name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2          

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm install cypress --save-dev
          npm i -g chromedriver@117.0.5938.88
          npm install -g @axe-core/cli
          
        
      # - name: Run Cypress Tests
      #   run: npx cypress run

      - name: Run Accessibility Checks
        run: 
          npx axe --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver --stdout https://qxf2.com/selenium-tutorial-main --tags wcag2a --verbose --show-errors --exit        

